### ISSUE TITLE
Error when sending request.

### ISSUE THREAD

**Issue by Bongsakorn** [may-/cnn-ld-tf#1]
Hello, 

I got error as below when I send request to prediction.

TypeError: Expected int32, got list containing Tensors of type '_Message' instead

**Comment by may-** [comment]
Hello, thank you for your comments.

It seems that you are using a newer version of tensorflow. I've updated my code and the pre-trained model compatible with tensorflow 1.0. Please check your tensorflow version and try it again!

**Comment by Bongsakorn** [comment]
Thank you very much.
